register(GRAMPLET,
         id="Historical Context", 
         name=_("Historical Context"),
         description = _("Displaying a historical context"),
         status = EXPERIMENTAL,
         version = '0.0.10',
         fname="HistTimeLine.py",
         height = 20,
         detached_width = 510,
         detached_height = 480,
         expand = True,
         gramplet = "Historical Context",
         gramplet_title=_("Historical Context"),
         gramps_target_version="5.2",
         help_url="https://github.com/kajmikkelsen/TimeLineGramplet",
         navtypes=["Person","Dashboard"],
         )
