register(GRAMPLET,
         id="Historical Timeline", 
         name=_("Historical Timeline"),
         description = _("Displaying a historical timeline"),
         status = EXPERIMENTAL,
         version = '0.0.10',
         fname="HistTimeLine.py",
         height = 20,
         detached_width = 510,
         detached_height = 480,
         expand = True,
         gramplet = "HistoricalTimeLineGramplet",
         gramplet_title=_("Historical Timeline"),
         gramps_target_version="5.2",
         help_url="5.2_Addons#Addon_List",
         navtypes=["Person","Dashboard"],
         )
